### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Dinakami** [learn-co-curriculum/reading-ios-intro-to-xcode#13]
When I run my code (on Xcode), the simulator gives my a blank screen that looks nothing like an iPhone screen. Has anyone had this problem or know how to fix it?

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue, which we unfortunately do not have the capacity to support at this time. I would recommend googling around about the problem.

I'm sorry, and good luck! 🙂
