### ISSUE TITLE
The top tip section about the navigator is too complex

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/reading-ios-intro-to-xcode#4]
I got totally lost when reading the 'Top Tip' about the navigator. This section felt too complex to be in an 'intro to xcode' readme. I have no idea what CocoaPods, Specta, and Expecta are.

**Comment by markedwardmurray** [comment]
Thanks for making the note about this. I'll have to think about where else in the curriculum the note could go.

**Comment by markedwardmurray** [comment]
The old version of this reading has been copied to a new repo in the middle of this unit where that note should make better sense.
